echo ../miniRT "Errors/Corupted color.rt"
../miniRT "Errors/Corupted color.rt"
echo ../miniRT "Errors/Corupted vector.rt"
../miniRT "Errors/Corupted vector.rt"
echo ../miniRT "Errors/Empty.rt"
../miniRT "Errors/Empty.rt"
echo ../miniRT "Errors/Negative res.rt"
../miniRT "Errors/Negative res.rt"
echo ../miniRT "Errors/No ambience light.rt"
../miniRT "Errors/No ambience light.rt"
echo ../miniRT "Errors/No res.rt"
../miniRT "Errors/No res.rt"
echo ../miniRT "Errors/Too strong light.rt"
../miniRT "Errors/Too strong light.rt"
echo ../miniRT "Errors/Corupted coords.rt"
../miniRT "Errors/Corupted coords.rt"
echo ../miniRT "Errors/Wrong objectc.rt"
../miniRT "Errors/Wrong objectc.rt"
echo ../miniRT "Errors/Zero res.rt"
../miniRT "Errors/Zero res.rt"
echo ../miniRT "Errors/Negative light.rt"
../miniRT "Errors/Negative light.rt"
echo ../miniRT ""
../miniRT
echo ../miniRT "Errors/No ambience light.rt" "There is second arg"
../miniRT "Errors/No ambience light.rt" "There is second arg"
echo ../miniRT "No such file.rt"
../miniRT "No such file.rt"
echo ../miniRT "Wrong type of file"
../miniRT "Wrong type of file"
