# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ksilver <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/05/07 16:28:16 by ksilver           #+#    #+#              #
#    Updated: 2020/05/07 16:28:18 by ksilver          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

MANDATORY = ft_isdigit.o ft_strdup.o ft_strnstr.o ft_strchr.o ft_strncmp.o\
ft_isascii.o ft_itoa.o ft_calloc.o ft_isprint.o ft_memccpy.o ft_memcmp.o\
ft_isalpha.o ft_tolower.o ft_memset.o ft_putchar_fd.o ft_memchr.o ft_strjoin.o\
ft_memcpy.o ft_substr.o ft_strmapi.o ft_putnbr_fd.o ft_strtrim.o ft_memmove.o\
ft_strlcpy.o ft_split.o ft_toupper.o ft_strlen.o ft_putstr_fd.o ft_strrchr.o\
ft_isalnum.o ft_putendl_fd.o ft_atoi.o ft_strlcat.o ft_bzero.o ft_uitoa_base.o\
ft_uitoa.o ft_strins_fr.o ft_ultoa_base.o ft_ulltoa_base.o ft_mod.o ft_latoi.o\
ft_pwr_db.o ft_mod_db.o ft_atod.o dup_cpy.o get_next_line_utils.o\
get_next_line.o con_loc.o

.PHONY: all
all: $(NAME)

$(NAME): $(MANDATORY)
		@ar rc libft.a $(MANDATORY)
		ranlib libft.a

ft_isdigit.o: ft_isdigit.c
		gcc -c -Wall -Wextra -Werror ft_isdigit.c

ft_strdup.o: ft_strdup.c
		gcc -c -Wall -Wextra -Werror ft_strdup.c

ft_strnstr.o: ft_strnstr.c
		gcc -c -Wall -Wextra -Werror ft_strnstr.c

ft_strchr.o: ft_strchr.c
		gcc -c -Wall -Wextra -Werror ft_strchr.c

ft_strncmp.o: ft_strncmp.c
		gcc -c -Wall -Wextra -Werror ft_strncmp.c

ft_isascii.o: ft_isascii.c
		gcc -c -Wall -Wextra -Werror ft_isascii.c

ft_itoa.o: ft_itoa.c
		gcc -c -Wall -Wextra -Werror ft_itoa.c

ft_calloc.o: ft_calloc.c
		gcc -c -Wall -Wextra -Werror ft_calloc.c

ft_isprint.o: ft_isprint.c
		gcc -c -Wall -Wextra -Werror ft_isprint.c

ft_memccpy.o: ft_memccpy.c
		gcc -c -Wall -Wextra -Werror ft_memccpy.c

ft_memcmp.o: ft_memcmp.c
		gcc -c -Wall -Wextra -Werror ft_memcmp.c

ft_isalpha.o: ft_isalpha.c
		gcc -c -Wall -Wextra -Werror ft_isalpha.c

ft_tolower.o: ft_tolower.c
		gcc -c -Wall -Wextra -Werror ft_tolower.c

ft_memset.o: ft_memset.c
		gcc -c -Wall -Wextra -Werror ft_memset.c

ft_putchar_fd.o: ft_putchar_fd.c
		gcc -c -Wall -Wextra -Werror ft_putchar_fd.c

ft_memchr.o: ft_memchr.c
		gcc -c -Wall -Wextra -Werror ft_memchr.c

ft_strjoin.o: ft_strjoin.c
		gcc -c -Wall -Wextra -Werror ft_strjoin.c

ft_memcpy.o: ft_memcpy.c
		gcc -c -Wall -Wextra -Werror ft_memcpy.c

ft_substr.o: ft_substr.c
		gcc -c -Wall -Wextra -Werror ft_substr.c

ft_strmapi.o: ft_strmapi.c
		gcc -c -Wall -Wextra -Werror ft_strmapi.c

ft_putnbr_fd.o: ft_putnbr_fd.c
		gcc -c -Wall -Wextra -Werror ft_putnbr_fd.c

ft_strtrim.o: ft_strtrim.c
		gcc -c -Wall -Wextra -Werror ft_strtrim.c

ft_memmove.o: ft_memmove.c
		gcc -c -Wall -Wextra -Werror ft_memmove.c

ft_strlcpy.o: ft_strlcpy.c
		gcc -c -Wall -Wextra -Werror ft_strlcpy.c

ft_split.o: ft_split.c
		gcc -c -Wall -Wextra -Werror ft_split.c

ft_toupper.o: ft_toupper.c
		gcc -c -Wall -Wextra -Werror ft_toupper.c

ft_strlen.o: ft_strlen.c
		gcc -c -Wall -Wextra -Werror ft_strlen.c

ft_putstr_fd.o: ft_putstr_fd.c
		gcc -c -Wall -Wextra -Werror ft_putstr_fd.c

ft_strrchr.o: ft_strrchr.c
		gcc -c -Wall -Wextra -Werror ft_strrchr.c

ft_isalnum.o: ft_isalnum.c
		gcc -c -Wall -Wextra -Werror ft_isalnum.c

ft_putendl_fd.o: ft_putendl_fd.c
		gcc -c -Wall -Wextra -Werror ft_putendl_fd.c

ft_atoi.o: ft_atoi.c
		gcc -c -Wall -Wextra -Werror ft_atoi.c

ft_strlcat.o: ft_strlcat.c
		gcc -c -Wall -Wextra -Werror ft_strlcat.c

ft_bzero.o: ft_bzero.c
		gcc -c -Wall -Wextra -Werror ft_bzero.c
		
ft_uitoa_base.o: ft_uitoa_base.c
		gcc -c -Wall -Wextra -Werror ft_uitoa_base.c
		
ft_uitoa.o: ft_uitoa.c 
		gcc -c -Wall -Wextra -Werror ft_uitoa.c
		
ft_strins_fr.o: ft_strins_fr.c
		gcc -c -Wall -Wextra -Werror ft_strins_fr.c
		
ft_ultoa_base.o: ft_ultoa_base.c
		gcc -c -Wall -Wextra -Werror ft_ultoa_base.c

ft_ulltoa_base.o: ft_ulltoa_base.c
		gcc -c -Wall -Wextra -Werror ft_ulltoa_base.c

ft_mod.o: ft_mod.c
		gcc -c -Wall -Wextra -Werror ft_mod.c
		
ft_latoi.o: ft_latoi.c
		gcc -c -Wall -Wextra -Werror ft_latoi.c
		
ft_pwr_db.o: ft_pwr_db.c
		gcc -c -Wall -Wextra -Werror ft_pwr_db.c

ft_mod_db.o: ft_mod_db.c
		gcc -c -Wall -Wextra -Werror ft_mod_db.c

ft_atod.o: ft_atod.c
		gcc -c -Wall -Wextra -Werror ft_atod.c
		
dup_cpy.o: dup_cpy.c
		gcc -c -Wall -Wextra -Werror dup_cpy.c
		
get_next_line.o: GNL/get_next_line.c
		gcc -c -Wall -Wextra -Werror GNL/get_next_line.c

get_next_line_utils.o: GNL/get_next_line_utils.c
		gcc -c -Wall -Wextra -Werror GNL/get_next_line_utils.c
		
con_loc.o: con_loc.c
		gcc -c -Wall -Wextra -Werror con_loc.c
		
.PHONY: clean
clean:
		@rm -f $(MANDATORY) $(BONUS_PART)

.PHONY: fclean
fclean: clean
		rm -f $(NAME)

.PHONY: re
re: clean all	
